ktor:
  application:
    modules:
      - com.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password
jwt:
  secret: "secret"
  issuer: "http://localhost:8080"
  audience: "http://localhost:8080"
  expiry: "86400000"